# Generated by Django 5.0.4 on 2024-06-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='list_item_images/'),
        ),
    ]
