# Generated by Django 5.0.4 on 2024-06-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='list_title',
            field=models.CharField(default=1, max_length=100, verbose_name='Название списка'),
            preserve_default=False,
        ),
    ]
