# Generated by Django 5.0.4 on 2024-06-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_event_list_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='list_title',
            field=models.CharField(default='Название списка', max_length=255),
        ),
    ]
