# Generated by Django 5.0.4 on 2024-06-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_contactmessage_alter_event_list_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paragraph',
            new_name='Paragraph1',
        ),
    ]
