# Generated by Django 5.0.4 on 2024-06-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_rename_paragraph_paragraph1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paragraph1',
            new_name='Paragraph',
        ),
    ]
