# Generated by Django 5.0.4 on 2024-09-25 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_announcementimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='announcementimage',
            options={'verbose_name': 'Изображение объявления', 'verbose_name_plural': 'Изображения объявлений'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Сообщения обратной связи', 'verbose_name_plural': 'Сообщения обратной связи'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятия/Памятники', 'verbose_name_plural': 'Мероприятия/Памятники'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.AlterModelOptions(
            name='listitem',
            options={'verbose_name': 'Элемент списка', 'verbose_name_plural': 'Элементы списка'},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'verbose_name': 'Абзац', 'verbose_name_plural': 'Абзацы'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_past_event',
            field=models.BooleanField(default=False, verbose_name='На страницу "Памятники"'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='news.event')),
            ],
        ),
    ]
