# Generated by Django 5.0.4 on 2024-10-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_videogallery_delete_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Главная/Памятники', 'verbose_name_plural': 'Главная/Памятники'},
        ),
    ]
